config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/' => 'home#index'

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy', as: :log_out


  resources :users do
    resources :photos
  end
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :user_id, :presence => true
  validates :image, :presence => true
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :presence => true
  validates :password, :presence => true, :on => :create
  has_many :photos

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photos = Photo.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.new
  end

  def create
    @user = User.find(params[:user_id])
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:notice] = "Hey nice, you uploaded a photo, go you"
      redirect_to :back
    else
      flash[:notice] = "Oh uh you should like upload a picture or else whats the point tbh"
      redirect_to :back
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to :back
  end

private

  def photo_params
    params.require(:photo).permit(:user_id, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.authenticate(params[:username], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out."
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      flash[:notice] = "Congrats, you account was created! Please log in."
      redirect_to "/log-in"
    else
      flash[:alert] = "There was a problem creating your account, please try again."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
    @photos = Photo.where("user_id = ?", @user.id)
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You've updated your profile."
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem updating your info."
      redirect_to :back
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :avatar, :bio, :camera_type, :sea_creature)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Photo_Share&#8482;
<br>
  <small>
    &nbsp;&nbsp;Give us your <strike>data</strike> Pictures!
  </small>
</h1>
<p>

  <% @photos.each do |photo| %>
    <div class="col-xs-2 thumb-div" style="background: url('<%= photo.image.url(:medium)%>') no-repeat; background-size: cover;">
       <!-- image_tag photo.image.url(:thumb) %> -->
      <br>
      <div class="col-xs-12 thumb-info">
        &nbsp;<%= link_to photo.user.username, user_path(photo.user) %>
      </div>
    </div>

  <% end %>

</p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShare</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">

    <div class="header">
        <ul class="nav nav-pills">
          <li role="presentation">
            <%= link_to "Home", root_path %>
          </li>
          <% if current_user %>
          <li role="presentation">
            <%= link_to current_user.username, user_path(current_user.id) %>
          </li>
          <li role="presentation">
            <%= link_to "Log Out", log_out_path %>
          </li>
          <% else %>
          <li role="presentation">
            <%= link_to "New User", new_user_path %>
          </li>
          <li role="presentation">
            <%= link_to "Log In", log_in_path %>
          </li>
          <% end %>
        </ul>
    </div>

    <%= flash[:notice] %>
    <%= flash[:alert] %>
  <div class="col-md-12">
    <%= yield %>
  </div>

  </div>
</body>
</html>

app/views/photos/new.html.erb
<%= render "layouts/errors", :object => @user %>
<h1>Upload a new image!</h1>

<%= form_for [@user, @photo] do |f| %>
  <%=f.hidden_field :user_id, :value => @user.id%>
  <%=f.label :image %>
  <%= f.file_field :image %>
  <%= f.submit "Upload Image" %>
<% end %>

app/views/users/edit.html.erb
<%= render "layouts/errors", :object => @user %>

<h1>Edit your profile:</h1>
<%= form_for @user do |f| %>
<p>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
</p>
<p>
  <%= f.label :bio %>
  <%= f.text_field :bio %>
</p>
<p>
  <%= f.label :camera_type %>
  <%= f.text_field :camera_type %>
</p>
<p>
  <%= f.label "Favorite sea creature" %>
  <%= f.text_field :sea_creature %>
</p>
  <%= f.submit %>
<%end%>

app/views/users/new.html.erb
<%= render "layouts/errors", :object => @user %>

<h1>Create an account!</h1>
<%=form_for @user do |f| %>
  <%=f.label :username %>
  <%=f.text_field :username %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%=f.label :avatar %>
  <%= f.file_field :avatar %>

  <%=f.submit "Sign Up" %>
<%end%>

app/views/users/show.html.erb
<div class="col-md-3 user-prof">
  <h3><%= @user.username %>'s profile
    <br>
  <small>
    <% if current_user == @user %>
      <%= link_to "Edit Profile.", edit_user_path(@user) %> |
      <%= link_to "Upload a new image.", new_user_photo_path(@user) %>
    <% end %>
  </small>
  </h3>

  <%= image_tag @user.avatar.url(:thumb) %>
  <hr>
  <div class="row col-md-12 user-deets">
    "<%= @user.bio %>"
  </div>

  <div class="row col-md-12 user-deets">
    Camera: <%= @user.camera_type %>
  </div>

  <div class="row col-md-12 user-deets">
    Favorite sea creature: <%= @user.sea_creature %>
  </div>




</div>

  <% @photos.each do |photo| %>
  <div class="col-xs-3 medium-div" style="background: url('<%= photo.image.url(:medium)%>') no-repeat; background-size: cover;">
    <div class="col-xs-12 medium-info">
      &nbsp;<%= link_to "X", user_photo_path(@user, photo), :data => {:method => "delete"} %> | <%= Time.at(photo.image.updated_at).to_date %>
    </div>
  </div>
  <% end %>